version: "2"

linters:
  default: all
  disable:
    - gomodguard  # deprecated
    - wsl  # deprecated
    - depguard
    - dupl
    - mnd
  settings:
    goconst:
      ignore-tests: true
  exclusions:
    rules:
      # funlen on tests makes it difficult to write table-driven tests.
      - path: _test\.go
        linters: [funlen]

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
    - swaggo
